### ISSUE TITLE
e2e failure: timeout waiting for PVC to be ready

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#305]
logs:
```
07:14:04 time="2016-10-31T07:09:12Z" level=info msg="PV claim (test-etcd-nr6hy-pvc) status.phase: Pending" 
07:14:04 time="2016-10-31T07:09:14Z" level=info msg="PV claim (test-etcd-nr6hy-pvc) status.phase: Pending" 
07:14:04 time="2016-10-31T07:09:14Z" level=info msg="PV claim (test-etcd-nr6hy-pvc) status.phase: Pending" 
07:14:04 time="2016-10-31T07:09:14Z" level=error msg="fail to poll PVC (test-etcd-nr6hy-pvc): timed out waiting for the condition" 
07:14:04 panic: timed out waiting for the condition
07:14:04 
07:14:04 goroutine 50 [running]:
07:14:04 panic(0x18d9000, 0xc420160bc0)
07:14:04 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
07:14:04 github.com/coreos/kube-etcd-controller/pkg/controller.(*Controller).Run.func2(0xc4203d7b00, 0xc4203d78c0)
07:14:04 	/go/src/github.com/coreos/kube-etcd-controller/pkg/controller/controller.go:142 +0x4e4
07:14:04 created by github.com/coreos/kube-etcd-controller/pkg/controller.(*Controller).Run
07:14:04 	/go/src/github.com/coreos/kube-etcd-controller/pkg/controller/controller.go:153 +0x2e9
```

**Comment by hongchaodeng** [comment]
@xiang90 @lachie83

The creation and waiting of PVC should also sit inside reconcile loop.

**Comment by hongchaodeng** [comment]
Digging into this issue showed the following error info for PVC:
```
Name:		test-etcd-u69dm-pvc
Namespace:	test
Status:		Pending
Volume:
Labels:		etcd_cluster=test-etcd-u69dm
Capacity:
Access Modes:
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  54s		8s		5	{persistentvolume-controller }			Warning		ProvisioningFailed	no volume plugin matched
```

**Comment by hongchaodeng** [comment]
The panic should have been fixed.
Though the error could still exist. Gonna create a new issue.
