### ISSUE TITLE
(fix) Documentation of kubernetes.io/aws-ebs PV provisioner 

### ISSUE THREAD

**Issue by lachie83** [coreos/etcd-operator#337]
Conflicting statements on AWS PV provisioner support README
> (TODO: We are planning to support AWS EBS soon.)

> Backup requires PV to work, and it only works on AWS(kubernetes.io/aws-ebs) or GCE(kubernetes.io/gce-pd) for now.

Confirmed that it currently only works with kubernetes.io/gce-pd as a provisioner

Will provide PR

**Comment by lachie83** [comment]
Supporting evidence for cluster running v1.4.4 on AWS

```bash
$ kubectl get storageclass -o yaml
namespace:default
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
  metadata:
    creationTimestamp: 2016-11-04T18:32:49Z
    name: etcd-operator-backup
    resourceVersion: "1504976"
    selfLink: /apis/storage.k8s.io/v1beta1/storageclasses/etcd-operator-backup
    uid: 16c6b123-a2bd-11e6-a214-0295f91dc779
  provisioner: kubernetes.io/gce-pd
kind: List
metadata: {}
$ kubectl get pvc -o yaml
namespace:default
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: etcd-operator-backup
    creationTimestamp: 2016-11-04T22:16:49Z
    labels:
      etcd_cluster: etcd-cluster
    name: etcd-cluster-pvc
    namespace: default
    resourceVersion: "1536658"
    selfLink: /api/v1/namespaces/default/persistentvolumeclaims/etcd-cluster-pvc
    uid: 61ac8678-a2dc-11e6-a977-0622500788d9
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 512Mi
  status:
    phase: Pending
kind: List
metadata: {}
$ kubectl describe pvc
namespace:default
Name:		etcd-cluster-pvc
Namespace:	default
Status:		Pending
Volume:		
Labels:		etcd_cluster=etcd-cluster
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  10m		3s		44	{persistentvolume-controller }			Warning		ProvisioningFailed	no volume plugin matched
```

**Comment by lachie83** [comment]
Also - this causes the controller to crash
```
time="2016-11-04T22:16:59Z" level=error msg="fail to poll PVC (etcd-cluster-pvc): timed out waiting for the condition" 
panic: timed out waiting for the condition

goroutine 62 [running]:
panic(0x18dc520, 0xc420160bc0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/etcd-operator/pkg/controller.(*Controller).Run.func2(0xc4200d2180, 0xc4200d2a80)
	/go/src/github.com/coreos/etcd-operator/pkg/controller/controller.go:143 +0x4e4
created by github.com/coreos/etcd-operator/pkg/controller.(*Controller).Run
	/go/src/github.com/coreos/etcd-operator/pkg/controller/controller.go:154 +0x2e9
```

**Comment by hongchaodeng** [comment]
In the README, we have mentioned that AWS EBS as PV support is a TODO.

@lachie83 What's your concern here?

**Comment by lachie83** [comment]
At the bottom of the readme you then say 

> Backup requires PV to work, and it only works on AWS(kubernetes.io/aws-ebs) or GCE(kubernetes.io/gce-pd) for now.

**Comment by hongchaodeng** [comment]
Alright. We will change that. Thanks for reporting.

**Comment by lachie83** [comment]
PR is there

**Comment by lachie83** [comment]
Also what are your thoughts on catching that error to stop the controller crashing due to PV?

**Comment by xiang90** [comment]
@lachie83 Can you help to add AWS support?

**Comment by hongchaodeng** [comment]
closed via #338

**Comment by xiang90** [comment]
@hongchaodeng @lachie83 Can we create an issue for adding AWS EBS support? This seems a MUST HAVE.

**Comment by lachie83** [comment]
Sure - I will file an issue.

**Comment by lachie83** [comment]
looking at the code now. I can take a look at adding AWS support

**Comment by xiang90** [comment]
@lachie83 Awesome. Thanks!
