### ISSUE TITLE
MemberRemove() panic: Unexpected error from context packet: context deadline exceeded

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#664]
Encountered a panic in operator in jenkins causing test failure with change (https://github.com/coreos/etcd-operator/pull/663)

[logs](https://console.cloud.google.com/logs/viewer?project=coreos-k8s-scale-testing&authuser=1&minLogLevel=0&expandAll=false&resource=container%2Fcluster_name%2Fjenkins2%2Fnamespace_id%2Fe2e-etcd-operator-1008&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22jenkins%22%0Aresource.labels.namespace_id%3D%22e2e-etcd-operator-flaketest-977%22%0Aresource.labels.pod_id%3D%22etcd-operator%22%0ANOT%20%22reconciling%22%0A%0A&timestamp=2017-01-21T06:04:48.000000000Z):

```
panic: Unexpected error from context packet: context deadline exceeded
...
github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*clusterClient).MemberRemove(0xc4200c2168, 0x7f263eb2d018, 0xc4207b2660, 0xc4203fb9f8, 0x0, 0x0, 0x0, 0x10, 0x1300000010, 0x4)
...
github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3.(*cluster).MemberRemove(0xc4203fba10, 0x7f263eb2d018, 0xc4207b2660, 0x83db931eee8ef098, 0xc4207b2660, 0xc4203fba90, 0x0)
...
github.com/coreos/etcd-operator/pkg/util/etcdutil.RemoveMember(0xc420877d10, 0x3, 0x3, 0x83db931eee8ef098, 0x0, 0x0)
```

**Comment by hongchaodeng** [comment]
Seems to be panicking all the time.
```
panic: Unexpected error from context packet: context deadline exceeded

goroutine 568 [running]:
panic(0x14b8700, 0xc4201f5150)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/etcd-operator/vendor/google.golang.org/grpc/transport.ContextErr(0x20bcd20, 0x2141378, 0x2141378, 0x1, 0xc42027e9b0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/google.golang.org/grpc/transport/transport.go:549 +0x213
github.com/coreos/etcd-operator/vendor/google.golang.org/grpc/transport.(*Stream).Header(0xc42067d680, 0x17efeb8, 0xc42080b3f8, 0x20cfba0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/google.golang.org/grpc/transport/transport.go:241 +0x11a
github.com/coreos/etcd-operator/vendor/google.golang.org/grpc.recvResponse(0x20cbae0, 0x2141378, 0x0, 0x0, 0x0, 0x0, 0x20be160, 0xc420655200, 0x20cd980, 0xc420216400, ...)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/google.golang.org/grpc/call.go:62 +0xad
github.com/coreos/etcd-operator/vendor/google.golang.org/grpc.Invoke(0x7f9f38065800, 0xc420784660, 0x1730746, 0x22, 0x161eaa0, 0xc42027e930, 0x162e300, 0xc420020b98, 0xc4201a6c00, 0x0, ...)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/google.golang.org/grpc/call.go:202 +0x8a1
github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*clusterClient).MemberRemove(0xc420020b50, 0x7f9f38065800, 0xc420784660, 0xc42027e930, 0x0, 0x0, 0x0, 0x10, 0x1300000010, 0x4)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2737 +0xd2
github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3.(*retryClusterClient).MemberRemove.func1(0x7f9f38065800, 0xc420784660, 0x17ea27d, 0xc41fff44a7)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3/retry.go:143 +0x8c
github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3.(*Client).newRetryWrapper.func1(0x7f9f38065800, 0xc420784660, 0xc420176ac0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3/retry.go:31 +0x61
github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3.(*retryClusterClient).MemberRemove(0xc4206854e0, 0x7f9f38065800, 0xc420784660, 0xc42027e930, 0x0, 0x0, 0x0, 0x40e07f, 0x159a720, 0x15d7c40)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3/retry.go:145 +0x14e
github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3.(*cluster).MemberRemove(0xc42027e8e0, 0x7f9f38065800, 0xc420784660, 0xb607dd35bf387782, 0xc420784660, 0xc42027e920, 0x0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/vendor/github.com/coreos/etcd/clientv3/cluster.go:67 +0x8e
github.com/coreos/etcd-operator/pkg/util/etcdutil.RemoveMember(0xc4202347b0, 0x3, 0x3, 0xb607dd35bf387782, 0x0, 0x0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/pkg/util/etcdutil/etcdutil.go:59 +0x1e8
github.com/coreos/etcd-operator/pkg/cluster.(*Cluster).removeMember(0xc4200fc900, 0xc42083ae10, 0x14, 0xc42080bac0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/pkg/cluster/reconcile.go:165 +0x82
github.com/coreos/etcd-operator/pkg/cluster.(*Cluster).removeDeadMember(0xc4200fc900, 0xc42083ae10, 0xc4202346f0, 0x0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/pkg/cluster/reconcile.go:161 +0xee
github.com/coreos/etcd-operator/pkg/cluster.(*Cluster).reconcileMembers(0xc4200fc900, 0xc420234570, 0x0, 0x0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/pkg/cluster/reconcile.go:99 +0x3f3
github.com/coreos/etcd-operator/pkg/cluster.(*Cluster).reconcile(0xc4200fc900, 0xc420263320, 0x2, 0x2, 0x0, 0x0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/pkg/cluster/reconcile.go:48 +0x260
github.com/coreos/etcd-operator/pkg/cluster.(*Cluster).run(0xc4200fc900, 0xc420724ae0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/pkg/cluster/cluster.go:292 +0x8de
github.com/coreos/etcd-operator/pkg/cluster.New.func1(0xc42029e3a8, 0xc4200fc900, 0xc420724ae0)
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/pkg/cluster/cluster.go:120 +0x362
created by github.com/coreos/etcd-operator/pkg/cluster.New
	/home/jenkins/workspace/build-etcd-operator-1209/gopath/src/github.com/coreos/etcd-operator/pkg/cluster/cluster.go:121 +0x3b3
```

**Comment by hongchaodeng** [comment]
Seems to have recovered on the same commit: https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-flaketest/978/

**Comment by hongchaodeng** [comment]
I see. This seems to be using the wrong "context" package.
